# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p149hWnyUTHIyaBoo8q9nDGPLSc6FZZd
"""

ID_Item,Categoria,Marca,Tamanho,Data_Entrada,Data_Venda,Custo_Aquisicao,Preco_Venda,Status
IT001,Calça Jeans,Levi's,40,2025-08-01,2025-08-15,30.00,120.00,Vendido
IT002,Vestido de Festa,Zara,M,2025-08-01,,40.00,150.00,Disponível
IT003,Camiseta de Banda,H&M,G,2025-08-02,2025-08-10,15.00,60.00,Vendido
IT004,Bolsa de Couro,Arezzo,UN,2025-08-03,,50.00,200.00,Disponível
IT005,Calça Jeans,Renner,38,2025-08-05,2025-09-01,25.00,90.00,Vendido
IT006,Sapato Scarpin,Schutz,36,2025-08-05,2025-08-20,35.00,110.00,Vendido
IT007,Jaqueta de Couro,Genérica,M,2025-08-10,,60.00,250.00,Disponível
IT008,Camiseta de Banda,C&A,P,2025-08-11,2025-08-14,10.00,55.00,Vendido
IT009,Calça Jeans,C&A,42,2025-08-12,,20.00,80.00,Disponível
IT010,Vestido de Festa,Genérica,P,2025-08-15,2025-09-10,20.00,95.00,Vendido

csv_data = """ID_Item,Categoria,Marca,Tamanho,Data_Entrada,Data_Venda,Custo_Aquisicao,Preco_Venda,Status
IT001,Calça Jeans,Levi's,40,2025-08-01,2025-08-15,30.00,120.00,Vendido
IT002,Vestido de Festa,Zara,M,2025-08-01,,40.00,150.00,Disponível
IT003,Camiseta de Banda,H&M,G,2025-08-02,2025-08-10,15.00,60.00,Vendido
IT004,Bolsa de Couro,Arezzo,UN,2025-08-03,,50.00,200.00,Disponível
IT005,Calça Jeans,Renner,38,2025-08-05,2025-09-01,25.00,90.00,Vendido
IT006,Sapato Scarpin,Schutz,36,2025-08-05,2025-08-20,35.00,110.00,Vendido
IT007,Jaqueta de Couro,Genérica,M,2025-08-10,,60.00,250.00,Disponível
IT008,Camiseta de Banda,C&A,P,2025-08-11,2025-08-14,10.00,55.00,Vendido
IT009,Calça Jeans,C&A,42,2025-08-12,,20.00,80.00,Disponível
IT010,Vestido de Festa,Genérica,P,2025-08-15,2025-09-10,20.00,95.00,Vendido
"""

with open('/tmp/data.csv', 'w') as f:
    f.write(csv_data)

import pandas as pd

df = pd.read_csv('/tmp/data.csv')
display(df.head())

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Comando mágico para mostrar os gráficos diretamente no notebook
# %matplotlib inline

# Melhorar a aparência dos gráficos
plt.style.use('seaborn-v0_8-whitegrid')

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Comando mágico para mostrar os gráficos diretamente no notebook
# %matplotlib inline

# Melhorar a aparência dos gráficos
plt.style.use('seaborn-v0_8-whitegrid')

# Caminho para o arquivo de dados
caminho_arquivo = '/tmp/data.csv'

# Carregar os dados, já convertendo as colunas de data
df = pd.read_csv(caminho_arquivo, parse_dates=['Data_Entrada', 'Data_Venda'])

# Exibir as 5 primeiras linhas para verificar
df.head()

# Filtra apenas itens vendidos para calcular faturamento
df_vendidos = df[df['Status'] == 'Vendido'].copy()

# Agrupa por categoria para somar o faturamento
faturamento_categoria = df_vendidos.groupby('Categoria')['Preco_Venda'].sum().sort_values(ascending=False)
df_abc = faturamento_categoria.reset_index()
df_abc.rename(columns={'Preco_Venda': 'Faturamento'}, inplace=True)

# Calcula a participação individual e acumulada
df_abc['Participacao_%'] = (df_abc['Faturamento'] / df_abc['Faturamento'].sum()) * 100
df_abc['Acumulado_%'] = df_abc['Participacao_%'].cumsum()

# Classifica as categorias
def classificar_categoria(percentual_acumulado):
    if percentual_acumulado <= 80:
        return 'A'
    elif 80 < percentual_acumulado <= 95:
        return 'B'
    else:
        return 'C'

df_abc['Classe'] = df_abc['Acumulado_%'].apply(classificar_categoria)

# Exibir o resultado da análise ABC
df_abc

fig, ax1 = plt.subplots(figsize=(10, 6))

# Gráfico de barras para o faturamento por categoria
ax1.bar(df_abc['Categoria'], df_abc['Faturamento'], color='skyblue', label='Faturamento')
ax1.set_ylabel('Faturamento (R$)')
plt.xticks(rotation=45, ha='right')

# Gráfico de linha para o percentual acumulado
ax2 = ax1.twinx()
ax2.plot(df_abc['Categoria'], df_abc['Acumulado_%'], color='red', marker='o', linestyle='--', label='Acumulado %')
ax2.set_ylabel('Percentual Acumulado (%)')
ax2.set_ylim(0, 105)

# Título
fig.suptitle('Análise de Pareto por Categoria de Produtos', fontsize=16)
plt.show()

# Filtra os vendidos para calcular giro e margem
df_vendidos['Tempo_Permanencia'] = (df_vendidos['Data_Venda'] - df_vendidos['Data_Entrada']).dt.days
df_vendidos['Lucro'] = df_vendidos['Preco_Venda'] - df_vendidos['Custo_Aquisicao']
df_vendidos['Margem_%'] = (df_vendidos['Lucro'] / df_vendidos['Preco_Venda']) * 100

# Agrupa para obter as médias por categoria
giro_categoria = df_vendidos.groupby('Categoria')['Tempo_Permanencia'].mean().round(0).reset_index()
margem_categoria = df_vendidos.groupby('Categoria')['Margem_%'].mean().round(1).reset_index()

# Conta as peças
estoque_atual = df[df['Status'] == 'Disponível']['Categoria'].value_counts().reset_index(name='Pecas_Estoque')
total_vendido = df[df['Status'] == 'Vendido']['Categoria'].value_counts().reset_index(name='Pecas_Vendidas')

# Une tudo em uma tabela final de desempenho
df_desempenho = pd.merge(giro_categoria, margem_categoria, on='Categoria', how='outer')
df_desempenho = pd.merge(df_desempenho, estoque_atual, on='Categoria', how='outer')
df_desempenho = pd.merge(df_desempenho, total_vendido, on='Categoria', how='outer')
df_desempenho.fillna(0, inplace=True)

# Gera os insights
def gerar_insight(row):
    if row['Tempo_Permanencia'] <= 30 and row['Pecas_Estoque'] <= 5:
        return "🔥 PRIORIZAR GARIMPO"
    if row['Tempo_Permanencia'] > 90 and row['Pecas_Estoque'] > 5:
        return "❄️ CONSIDERAR PROMOÇÃO"
    if row['Margem_%'] > 60 and row['Tempo_Permanencia'] <= 45:
        return "⭐ JOIA RARA (ALTA MARGEM E GIRO)"
    return "OK"
df_desempenho['Insight'] = df_desempenho.apply(gerar_insight, axis=1)

# Organiza e renomeia
df_desempenho = df_desempenho[['Categoria', 'Pecas_Estoque', 'Pecas_Vendidas', 'Tempo_Permanencia', 'Margem_%', 'Insight']]
df_desempenho.rename(columns={'Tempo_Permanencia': 'Giro_Medio_Dias'}, inplace=True)

# Exibe a tabela de insights estratégicos
df_desempenho

fig, ax = plt.subplots(figsize=(12, 8))

# O tamanho da bolha (s) pode representar a margem de lucro, e a cor (c) também
scatter = ax.scatter(
    df_desempenho['Giro_Medio_Dias'],
    df_desempenho['Pecas_Vendidas'],
    s=df_desempenho['Margem_%'] * 8, # Multiplicador para as bolhas ficarem visíveis
    c=df_desempenho['Margem_%'],
    cmap='viridis', # Escala de cores
    alpha=0.7
)

# Adicionar rótulos para cada categoria
for i, row in df_desempenho.iterrows():
    ax.text(row['Giro_Medio_Dias'] + 0.5, row['Pecas_Vendidas'], row['Categoria'], fontsize=10, weight='bold')

# Linhas de média para dividir em quadrantes
media_giro = df_desempenho['Giro_Medio_Dias'].mean()
media_vendas = df_desempenho['Pecas_Vendidas'].mean()
ax.axvline(media_giro, color='grey', linestyle='--')
ax.axhline(media_vendas, color='grey', linestyle='--')

# Títulos e rótulos
ax.set_title('Matriz de Desempenho de Categorias', fontsize=18, weight='bold')
ax.set_xlabel('Giro Médio (Dias para Vender) <-- Mais Rápido | Mais Lento -->')
ax.set_ylabel('Total de Peças Vendidas')
fig.colorbar(scatter, label='Margem de Lucro Média (%)')

# Anotações dos Quadrantes
ax.text(media_giro / 2, media_vendas * 1.5, 'Estrelas\n(Giro Rápido, Vende Muito)', color='darkgreen', ha='center', fontsize=12)
ax.text(media_giro * 1.5, media_vendas * 0.5, 'Abacaxis\n(Giro Lento, Vende Pouco)', color='darkred', ha='center', fontsize=12)

plt.show()

import tkinter as tk
from tkinter import ttk
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import (
    FigureCanvasTkAgg,
    NavigationToolbar2Tk
)
import numpy as np

class AppGrafico(tk.Tk):
    """
    Classe principal da aplicação que herda de tk.Tk para criar a janela principal.
    """
    def __init__(self):
        super().__init__()

        # --- 1. Configuração da Janela Principal ---
        self.title("Gráfico Matplotlib no Tkinter")
        self.geometry("800x600")

        # --- 2. Criação dos Widgets ---
        # Frame para conter os botões
        frame_botoes = ttk.Frame(self)
        frame_botoes.pack(pady=10)

        # Botão para atualizar o gráfico
        self.botao_atualizar = ttk.Button(
            frame_botoes,
            text="Atualizar Gráfico",
            command=self.desenhar_grafico # Ação que o botão executa
        )
        self.botao_atualizar.pack(side=tk.LEFT, padx=5)

        # Frame que vai conter o gráfico
        self.frame_grafico = ttk.Frame(self)
        self.frame_grafico.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)

        # Variável para armazenar a referência do canvas do gráfico
        self.canvas = None

        # --- 3. Desenhar o Gráfico Inicial ---
        self.desenhar_grafico()

    def desenhar_grafico(self):
        """
        Função para gerar e desenhar o gráfico de barras na interface.
        """
        # --- A. Limpeza do Gráfico Anterior (IMPORTANTE!) ---
        # Se um canvas já existe, ele é destruído para dar lugar ao novo.
        # Isso evita que múltiplos gráficos sejam sobrepostos.
        if self.canvas:
            self.canvas.get_tk_widget().destroy()

        # --- B. Geração de Dados Fictícios ---
        categorias = ['Vendas', 'Marketing', 'TI', 'RH', 'Logística']
        valores = np.random.randint(low=10, high=100, size=len(categorias))

        # --- C. Criação da Figura e do Gráfico Matplotlib ---
        # 1. Cria uma figura Matplotlib. O 'dpi' controla a resolução.
        figura = Figure(figsize=(5, 4), dpi=100)

        # 2. Adiciona um subplot (eixo/área de desenho) à figura.
        # '111' significa uma grade de 1x1, primeiro subplot.
        eixo = figura.add_subplot(111)

        # 3. Cria o gráfico de barras no eixo definido.
        eixo.bar(categorias, valores, color='skyblue')

        # 4. Adiciona títulos e rótulos para clareza
        eixo.set_title("Desempenho por Departamento")
        eixo.set_xlabel("Departamentos")
        eixo.set_ylabel("Valores")
        figura.tight_layout() # Ajusta o gráfico para caber na figura

        # --- D. Incorporação do Gráfico no Tkinter ---
        # 1. Cria o canvas do Tkinter que vai conter a figura Matplotlib.
        self.canvas = FigureCanvasTkAgg(figura, master=self.frame_grafico)
        self.canvas.draw() # Desenha o gráfico no canvas

        # 2. Empacota o widget do canvas na janela (como qualquer outro widget Tkinter).
        self.canvas.get_tk_widget().pack(side=tk.TOP, fill=tk.BOTH, expand=True)

        # (Opcional) Adiciona a barra de ferramentas de navegação do Matplotlib
        toolbar = NavigationToolbar2Tk(self.canvas, self.frame_grafico)
        toolbar.update()
        self.canvas.get_tk_widget().pack()

if __name__ == "__main__":
    app = AppGrafico()
    app.mainloop()